version: '3.8'

services:
  app:
    user: "${UID}:${GID}"
    build: .
    container_name: mx-rag-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src/data:/app/src/data
      - ./src/pdfs:/app/src/pdfs:ro
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
